<?php

declare(strict_types=1);

namespace J7\PowerCheckout\Domains\Payment\ShoplinePayment\Shared\Enums;

/**
 * Shopline Payment 錯誤碼
 *
 * @see https://docs.shoplinepayments.com/appendix/errorCode/
 */
enum ErrorCode: string {

	case E_1005                = '1005';
	case E_1006                = '1006';
	case E_1008                = '1008';
	case E_1016                = '1016';
	case E_1018                = '1018';
	case E_1901                = '1901';
	case E_1902                = '1902';
	case E_1904                = '1904';
	case E_1997                = '1997';
	case E_1998                = '1998';
	case E_1999                = '1999';
	case E_2001                = '2001';
	case E_2002                = '2002';
	case E_2003                = '2003';
	case E_2004                = '2004';
	case E_2005                = '2005';
	case E_2006                = '2006';
	case E_2007                = '2007';
	case E_2008                = '2008';
	case E_2009                = '2009';
	case E_2010                = '2010';
	case E_2011                = '2011';
	case E_2013                = '2013';
	case E_URL_NOT_FOUND       = 'URL_NOT_FOUND';
	case E_ACCESS_DENIED       = 'ACCESS_DENIED';
	case E_MERCHANT_NOT_EXISTS = 'MERCHANT_NOT_EXISTS';
	case E_UNAUTHORIZED_CLIENT = 'UNAUTHORIZED_CLIENT';
	case E_SERVER_ERROR        = 'SERVER_ERROR';
	case E_KEY_INCORRECT       = 'KEY_INCORRECT';
	case E_INVALID_SCOPE       = 'INVALID_SCOPE';
	case E_1001                = '1001';
	case E_1003                = '1003';
	case E_1004                = '1004';
	case E_1025                = '1025';
	case E_4001                = '4001';
	case E_4002                = '4002';
	case E_4003                = '4003';
	case E_4101                = '4101';
	case E_4102                = '4102';
	case E_4103                = '4103';
	case E_4104                = '4104';
	case E_4105                = '4105';
	case E_4106                = '4106';
	case E_4107                = '4107';
	case E_4108                = '4108';
	case E_4109                = '4109';
	case E_3000                = '3000';
	case E_3001                = '3001';
	case E_3002                = '3002';
	case E_3003                = '3003';
	case E_3004                = '3004';
	case E_1012                = '1012';
	case E_4350                = '4350';
	case E_4400                = '4400';
	case E_4401                = '4401';
	case E_4402                = '4402';
	case E_4403                = '4403';
	case E_4404                = '4404';
	case E_4405                = '4405';
	case E_4406                = '4406';
	case E_4407                = '4407';
	case E_4408                = '4408';
	case E_4409                = '4409';
	case E_4410                = '4410';
	case E_4411                = '4411';
	case E_4412                = '4412';
	case E_4450                = '4450';
	case E_4451                = '4451';
	case E_4452                = '4452';
	case E_4453                = '4453';
	case E_4454                = '4454';
	case E_4455                = '4455';
	case E_4456                = '4456';
	case E_4457                = '4457';
	case E_4458                = '4458';
	case E_4459                = '4459';
	case E_4460                = '4460';
	case E_4461                = '4461';
	case E_4462                = '4462';
	case E_4463                = '4463';
	case E_4464                = '4464';
	case E_4465                = '4465';
	case E_4466                = '4466';
	case E_4467                = '4467';
	case E_4468                = '4468';
	case E_4550                = '4550';
	case E_4551                = '4551';
	case E_4552                = '4552';
	case E_4600                = '4600';
	case E_1010                = '1010';
	case E_1013                = '1013';
	case E_1014                = '1014';
	case E_1015                = '1015';
	case E_1020                = '1020';
	case E_1021                = '1021';
	case E_1202                = '1202';
	case E_1022                = '1022';
	case E_1023                = '1023';
	case E_4502                = '4502';
	case E_4701                = '4701';
	case E_4702                = '4702';
	case E_4703                = '4703';
	case E_4704                = '4704';
	case E_4705                = '4705';
	case E_4706                = '4706';
	case E_4707                = '4707';
	case E_4700                = '4700';
	case E_1200                = '1200';
	case E_1201                = '1201';
	case E_4800                = '4800';
	case E_4801                = '4801';
	case E_4802                = '4802';
	case E_1203                = '1203';
	case E_4900                = '4900';
	case E_4901                = '4901';
	case E_4902                = '4902';
	case E_6001                = '6001';
	case E_6002                = '6002';
	case E_6003                = '6003';
	case E_6400                = '6400';
	case E_6401                = '6401';
	case E_7001                = '7001';
	case E_7002                = '7002';
	case E_7400                = '7400';
	case E_7401                = '7401';
	case E_7402                = '7402';
	case E_7403                = '7403';
	case E_1009                = '1009';
	case E_4200                = '4200';
	case E_4201                = '4201';
	case E_4202                = '4202';
	case E_4203                = '4203';
	case E_4204                = '4204';
	case E_1026                = '1026';
	case E_1027                = '1027';
	case E_1028                = '1028';
	case E_1029                = '1029';
	case E_1100                = '1100';
	case E_1101                = '1101';
	case E_1102                = '1102';
	case E_1105                = '1105';
	case E_1106                = '1106';
	case E_1107                = '1107';
	case E_1108                = '1108';
	case E_1109                = '1109';
	case E_1111                = '1111';
	case E_1112                = '1112';
	case E_4110                = '4110';
	case E_4111                = '4111';
	case E_4205                = '4205';
	case E_4206                = '4206';
	case E_4207                = '4207';
	case E_4208                = '4208';
	case E_43000               = '43000';
	case E_43001               = '43001';
	case E_43002               = '43002';
	case E_43003               = '43003';
	case E_43004               = '43004';
	case E_43005               = '43005';
	case E_43006               = '43006';
	case E_43007               = '43007';
	case E_43008               = '43008';
	case E_43009               = '43009';
	case E_43010               = '43010';
	case E_43011               = '43011';

	/** @return string label */
	public function label(): string {
		$mapper = [
			self::E_1005->value                => \__('校驗錯誤', 'power_checkout'),
			self::E_1006->value                => \__('紀錄錄已存在', 'power_checkout'),
			self::E_1008->value                => \__('狀態錯誤', 'power_checkout'),
			self::E_1016->value                => \__('付款查詢、退款發起請求時，沒有交易紀錄', 'power_checkout'),
			self::E_1018->value                => \__('付款失敗/取消/逾期 & 未知原因', 'power_checkout'),
			self::E_1901->value                => \__('系統連線失敗', 'power_checkout'),
			self::E_1902->value                => \__('系統內部格式錯誤', 'power_checkout'),
			self::E_1904->value                => \__('請求過於頻繁', 'power_checkout'),
			self::E_1997->value                => \__('資料庫錯誤', 'power_checkout'),
			self::E_1998->value                => \__('系統配置錯誤', 'power_checkout'),
			self::E_1999->value                => \__('系統異常', 'power_checkout'),
			self::E_2001->value                => \__('APPID不存在', 'power_checkout'),
			self::E_2002->value                => \__('簽名錯誤', 'power_checkout'),
			self::E_2003->value                => \__('請求URL錯誤', 'power_checkout'),
			self::E_2004->value                => \__('系統內部錯誤', 'power_checkout'),
			self::E_2005->value                => \__('訪問拒絕', 'power_checkout'),
			self::E_2006->value                => \__('錯誤請求', 'power_checkout'),
			self::E_2007->value                => \__('無法訪問', 'power_checkout'),
			self::E_2008->value                => \__('服務無法存取', 'power_checkout'),
			self::E_2009->value                => \__('Token逾期', 'power_checkout'),
			self::E_2010->value                => \__('Token被篡改', 'power_checkout'),
			self::E_2011->value                => \__('付款工具狀態禁止修改', 'power_checkout'),
			self::E_2013->value                => \__('商戶未與平台 Connect', 'power_checkout'),
			self::E_URL_NOT_FOUND->value       => \__('URL不存在', 'power_checkout'),
			self::E_ACCESS_DENIED->value       => \__('apiKey 或 clientKey 不正確/秘鑰與商家ID或平台ID不符/秘鑰錯誤/商家沒有存取資源權限', 'power_checkout'),
			self::E_MERCHANT_NOT_EXISTS->value => \__('特店ID不存在', 'power_checkout'),
			self::E_UNAUTHORIZED_CLIENT->value => \__('客戶端ID錯誤或授權參數錯誤', 'power_checkout'),
			self::E_SERVER_ERROR->value        => \__('其他系統錯誤', 'power_checkout'),
			self::E_KEY_INCORRECT->value       => \__('平台 Authorize觸發 connect綁定的時 apiKey錯誤', 'power_checkout'),
			self::E_INVALID_SCOPE->value       => \__('授權範圍錯誤', 'power_checkout'),
			self::E_1001->value                => \__('重複下單，交易已存在', 'power_checkout'),
			self::E_1003->value                => \__('下單過程中，參數缺失', 'power_checkout'),
			self::E_1004->value                => \__('下單請求過程中，因入參錯誤等系統原因導致的下單失敗', 'power_checkout'),
			self::E_1025->value                => \__('下單請求過程中，超過最大付款限額或不足最低付款限額', 'power_checkout'),
			self::E_4001->value                => \__('通路連線失敗', 'power_checkout'),
			self::E_4002->value                => \__('通路錯誤', 'power_checkout'),
			self::E_4003->value                => \__('通路回應逾時', 'power_checkout'),
			self::E_4101->value                => \__('付款超額，付款金額不在最低和最高限額之間', 'power_checkout'),
			self::E_4102->value                => \__('發起請求過程中，因為交易異常情況，下單失敗', 'power_checkout'),
			self::E_4103->value                => \__('因為列表以外的未知原因導致下單失敗', 'power_checkout'),
			self::E_4104->value                => \__('因為特店帳戶狀態異常，導致交易下單被拒絕。', 'power_checkout'),
			self::E_4105->value                => \__('由於顧客帳戶狀態異常，導致交易失敗', 'power_checkout'),
			self::E_4106->value                => \__('IP位址在通路側未加入白名單', 'power_checkout'),
			self::E_4107->value                => \__('交易幣種通路不支援', 'power_checkout'),
			self::E_4108->value                => \__('喚起付款表單失敗', 'power_checkout'),
			self::E_4109->value                => \__('網站網域未設定', 'power_checkout'),
			self::E_3000->value                => \__('命中 SLP 風控，使用者行為異常', 'power_checkout'),
			self::E_3001->value                => \__('命中 SLP 風控，交易卡異常', 'power_checkout'),
			self::E_3002->value                => \__('命中 SLP 風控，收貨人資訊異常', 'power_checkout'),
			self::E_3003->value                => \__('命中 SLP 風控，高風險交易', 'power_checkout'),
			self::E_3004->value                => \__('命中 SLP 風控，交易資訊異常', 'power_checkout'),
			self::E_1012->value                => \__('特店 SLP 付款權限已停用', 'power_checkout'),
			self::E_4350->value                => \__('命中通路/銀行風控，交易被拒絕', 'power_checkout'),
			self::E_4400->value                => \__('通路測交易過程中資料傳輸異常、系統異常', 'power_checkout'),
			self::E_4401->value                => \__('通路測交易交易逾期', 'power_checkout'),
			self::E_4402->value                => \__('ATM 虛擬帳號場景：客戶實際繳款金額與產生帳號的金額不一致', 'power_checkout'),
			self::E_4403->value                => \__('系統繁忙', 'power_checkout'),
			self::E_4404->value                => \__('付款完成後，token內與付款請求內金額錯誤', 'power_checkout'),
			self::E_4405->value                => \__('與錢包前端互動後，回應的token非法', 'power_checkout'),
			self::E_4406->value                => \__('付款公鑰錯誤', 'power_checkout'),
			self::E_4407->value                => \__('付款私鑰錯誤', 'power_checkout'),
			self::E_4408->value                => \__('付款簽名錯誤', 'power_checkout'),
			self::E_4409->value                => \__('與通路前端互動後，回傳的token逾期', 'power_checkout'),
			self::E_4410->value                => \__('與通路互動後，通路提示重複付款', 'power_checkout'),
			self::E_4411->value                => \__('通路介面回傳鑑權失敗', 'power_checkout'),
			self::E_4412->value                => \__('通路介面回應not found', 'power_checkout'),
			self::E_4450->value                => \__('銀行卡付款中，3DS驗證流程逾時', 'power_checkout'),
			self::E_4451->value                => \__('發卡行回傳信用卡交易失敗', 'power_checkout'),
			self::E_4452->value                => \__('銀行卡付款中，3DS交驗不通過', 'power_checkout'),
			self::E_4453->value                => \__('銀行卡CVV2驗證不通過', 'power_checkout'),
			self::E_4454->value                => \__('交易卡餘額不足', 'power_checkout'),
			self::E_4455->value                => \__('交易卡卡號驗證不通過（卡號無效）', 'power_checkout'),
			self::E_4456->value                => \__('通路側系統異常', 'power_checkout'),
			self::E_4457->value                => \__('發卡行識別出為高風險交易', 'power_checkout'),
			self::E_4458->value                => \__('交易依然pending在通路側，處理中', 'power_checkout'),
			self::E_4459->value                => \__('發卡銀行識別出銀行卡已過有效期限', 'power_checkout'),
			self::E_4460->value                => \__('發卡行回傳交易密碼輸入次數超額限額', 'power_checkout'),
			self::E_4461->value                => \__('發卡行回傳交易金額超過最大/最小限額', 'power_checkout'),
			self::E_4462->value                => \__('發卡行回傳交易密碼檢定不通過', 'power_checkout'),
			self::E_4463->value                => \__('發卡銀行識別出交易卡為被竊/遺失卡', 'power_checkout'),
			self::E_4464->value                => \__('卡被凍結', 'power_checkout'),
			self::E_4465->value                => \__('輸入PIN', 'power_checkout'),
			self::E_4466->value                => \__('金融卡卡受限', 'power_checkout'),
			self::E_4467->value                => \__('已超交易次數', 'power_checkout'),
			self::E_4468->value                => \__('付款碼或收款碼已逾期或無效', 'power_checkout'),
			self::E_4550->value                => \__('客戶自主取消交易', 'power_checkout'),
			self::E_4551->value                => \__('客戶發起了拒付，交易正在爭議期', 'power_checkout'),
			self::E_4552->value                => \__('顧客付款帳號異常', 'power_checkout'),
			self::E_4600->value                => \__('Others-Exception', 'power_checkout'),
			self::E_1010->value                => \__('特店SLP退款權限已停用', 'power_checkout'),
			self::E_1013->value                => \__('退款要求已存在，不可重複發起退款', 'power_checkout'),
			self::E_1014->value                => \__('交易已完成全部金額退款，無可退款金額', 'power_checkout'),
			self::E_1015->value                => \__('特店帳戶未完成高級認證，不可發起退款', 'power_checkout'),
			self::E_1020->value                => \__('付款交易可以退款的時效為180天，如超過，無法退款', 'power_checkout'),
			self::E_1021->value                => \__('請求退款的交易交易不存在或狀態異常（失敗/逾時）', 'power_checkout'),
			self::E_1202->value                => \__('通路不支援線上退款API，只能線下退款', 'power_checkout'),
			self::E_1022->value                => \__('由於特店帳戶餘額不足，退款失敗', 'power_checkout'),
			self::E_1023->value                => \__('因為清單以外的未知原因導致退款失敗', 'power_checkout'),
			self::E_4502->value                => \__('請求退款的交易交易不存在或狀態異常（失敗/逾時）', 'power_checkout'),
			self::E_4701->value                => \__('退款要求金額超過交易可退款金額', 'power_checkout'),
			self::E_4702->value                => \__( '由於特店帳戶餘額不足，退款失敗', 'power_checkout' ),
			self::E_4703->value                => \__('付款交易已超過可退款時效', 'power_checkout'),
			self::E_4704->value                => \__('因為清單以外的未知原因導致退款失敗', 'power_checkout'),
			self::E_4705->value                => \__('傳輸金額不正確導致退款失敗', 'power_checkout'),
			self::E_4706->value                => \__('上次的退款交易尚在退款中，無法再新發起退款', 'power_checkout'),
			self::E_4707->value                => \__('該交易不支持部分退款', 'power_checkout'),
			self::E_4700->value                => \__('請求退款的交易交易不存在或狀態異常（失敗/逾時）', 'power_checkout'),
			self::E_1200->value                => \__('暫時不支援綁卡功能', 'power_checkout'),
			self::E_1201->value                => \__('系統正在自動處理綁卡後流程，請5分鐘後再試', 'power_checkout'),
			self::E_4800->value                => \__('未知原因', 'power_checkout'),
			self::E_4801->value                => \__('使用者拒絕授權', 'power_checkout'),
			self::E_4802->value                => \__('通路參數錯誤', 'power_checkout'),
			self::E_1203->value                => \__('通路進行卡片驗證，通路回應失敗', 'power_checkout'),
			self::E_4900->value                => \__('通路要求該筆交易需要進行3DS，但由於是顧客不在場定期付款，無法完成', 'power_checkout'),
			self::E_4901->value                => \__('通路要求該筆交易需要進行CVS認證，但由於是顧客不在場定期付款，無法完成', 'power_checkout'),
			self::E_4902->value                => \__('因其它原因，無法完成定期付款', 'power_checkout'),
			self::E_6001->value                => \__('交易處理中，交易取消失敗', 'power_checkout'),
			self::E_6002->value                => \__('交易已請款，無法取消', 'power_checkout'),
			self::E_6003->value                => \__('交易已取消，無法取消', 'power_checkout'),
			self::E_6400->value                => \__('交易狀態異常，無無法取消', 'power_checkout'),
			self::E_6401->value                => \__('通路系統原因導致無法取消', 'power_checkout'),
			self::E_7001->value                => \__('請款金額大於可請款金額', 'power_checkout'),
			self::E_7002->value                => \__('交易狀態異常，無法請款', 'power_checkout'),
			self::E_7400->value                => \__('交易狀態異常，無法請款', 'power_checkout'),
			self::E_7401->value                => \__('通路系統原因導致無法請款', 'power_checkout'),
			self::E_7402->value                => \__('請款金額大於可請款金額', 'power_checkout'),
			self::E_7403->value                => \__('因授權額度問題請款失敗', 'power_checkout'),
			self::E_1009->value                => \__('特店SLP收款權限已停用', 'power_checkout'),
			self::E_4200->value                => \__('特店暫未綁定該付款通路', 'power_checkout'),
			self::E_4201->value                => \__('特店暫無使用權限', 'power_checkout'),
			self::E_4202->value                => \__('通路或付款方式暫時不支援該交易幣種', 'power_checkout'),
			self::E_4203->value                => \__('特店收款帳戶狀態異常', 'power_checkout'),
			self::E_4204->value                => \__('暫不支援該付款方式', 'power_checkout'),
			self::E_1026->value                => \__('不支援瀏覽器', 'power_checkout'),
			self::E_1027->value                => \__('SDK 內部錯誤', 'power_checkout'),
			self::E_1028->value                => \__('初始化呈現失敗（兜底錯誤碼）', 'power_checkout'),
			self::E_1029->value                => \__('SDK 未完成呈現，呼叫了其他 API', 'power_checkout'),
			self::E_1100->value                => \__('當前設備環境不支援該付款方式', 'power_checkout'),
			self::E_1101->value                => \__('載入通路 JS 出錯', 'power_checkout'),
			self::E_1102->value                => \__('介面回應入參出錯，配置出錯', 'power_checkout'),
			self::E_1105->value                => \__('當前環境為非 HTTPS', 'power_checkout'),
			self::E_1106->value                => \__('建立訂單時脫離使用者操作', 'power_checkout'),
			self::E_1107->value                => \__('其他建立實例未識別到的錯誤', 'power_checkout'),
			self::E_1108->value                => \__('初始化 SDK 逾時', 'power_checkout'),
			self::E_1109->value                => \__('網路錯誤', 'power_checkout'),
			self::E_1111->value                => \__('載入內部 JS 出錯', 'power_checkout'),
			self::E_1112->value                => \__('顧客輸入錯誤', 'power_checkout'),
			self::E_4110->value                => \__('建立通道實例失敗', 'power_checkout'),
			self::E_4111->value                => \__('nextAction 入參出錯', 'power_checkout'),
			self::E_4205->value                => \__('交易異常（交易狀態未知）', 'power_checkout'),
			self::E_4206->value                => \__('該 API 不支援該付款方式', 'power_checkout'),
			self::E_4207->value                => \__('呈現 dom 不存在', 'power_checkout'),
			self::E_4208->value                => \__('SDK 入參出錯', 'power_checkout'),
			self::E_43000->value               => \__('目前卡的卡組不支援', 'power_checkout'),
			self::E_43001->value               => \__('目前卡的發卡銀行不支持', 'power_checkout'),
			self::E_43002->value               => \__('當前卡的卡類型不支援', 'power_checkout'),
			self::E_43003->value               => \__('目前卡片的發卡國家不支持', 'power_checkout'),
			self::E_43004->value               => \__('當前卡的卡等級不支持', 'power_checkout'),
			self::E_43005->value               => \__('目前卡片的卡片系列不支援(即卡bin不支援)', 'power_checkout'),
			self::E_43006->value               => \__('目前分期期數不支持', 'power_checkout'),
			self::E_43007->value               => \__('暫不支援該付款方式（目前特店ID不支援）', 'power_checkout'),
			self::E_43008->value               => \__('暫不支持此金額進行交易', 'power_checkout'),
			self::E_43009->value               => \__('目前付款方式正在維護中', 'power_checkout'),
			self::E_43010->value               => \__('身分資訊核驗異常', 'power_checkout'),
			self::E_43011->value               => \__('超出身分資訊核驗次數', 'power_checkout'),
		];

		return $mapper[ $this->value ];
	}
}
